name: actions-deploy
description: GitHub Actions-Based Release and Deployment
inputs:
  release:
    description: Command to run to perform release. Command is expected to create a release identified by the short git sha (`git rev-parse --short HEAD`). Environment variable `VERSION` will be available, or `git rev-parse --short HEAD` can be run to generate version.
    required: true
  deploy:
    description: Command to run to perform deploy. Environment variables `ENVIRONMENT` and `VERSION` will be available.
    required: true

  verify:
    description: Command to run to verify a deployment. Environment variables `ENVIRONMENT` and `VERSION` will be available.
    required: false
    default: 'echo No verify command provided'
  setup:
    description: Command to run before release, deploy, or verify
    required: false
    default: 'echo No setup command provided'
  production-environment:
    description: Name of the production environment
    required: false
    default: production
  pre-production-environment:
    description: Name of the pre-production environment
    required: false
    default: integration
runs:
  using: node12
  main: dist/index.js
branding:
  icon: upload-cloud
  color: blue
