on:
  release:
    types: [published]

name: Post Release
jobs:
  # Update README with new release version
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.repository.default_branch }}
    - run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
        sed -i 's,\(unbounce/actions-deploy@\)\(.*\),\1${{ github.event.release.tag_name }},g' README.md
        git add README.md
        git commit -m 'Update README for ${{ github.event.release.tag_name }}'
        git push origin ${{ github.event.repository.default_branch }}
