on:
  release:
    types: [published]

name: Post Release
jobs:
  # Update README with new release version
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.repository.default_branch }}
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        sed -i 's,\(unbounce/actions-deploy@\)\(.*\),\1${{ env.GITHUB_REF }},g' README.md
        git add README.md
        git commit -m 'Update README for ${{ env.GITHUB_REF }}'
        git push origin ${{ github.event.repository.default_branch }}
